// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvlwxezniwbqankmfclp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2bHd4ZXpuaXdicWFua21mY2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3OTEyNjksImV4cCI6MjA1NjM2NzI2OX0.uaI9vLKRMfeUXWYwMx8VBT1DSTweh4SR3cED08OgOfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);